SERVICENOW_QUERY = "active=true^priority<=3"
SERVICENOW_LIMIT = 20

EXCEL_FILE_PATH = "tickets.xlsx"
POLL_INTERVAL_SECONDS = 20

STALE_THRESHOLD_HOURS = 24
CRITICAL_THRESHOLD = 6
UPDATE_THRESHOLD = 3

ESCALATION_EMAIL = "lead@example.com"
TEAMS_WEBHOOK_URL = ""

EMAIL_SMTP_HOST = "smtp.example.com"
EMAIL_SMTP_PORT = 587
EMAIL_FROM = "alerts@example.com"
EMAIL_USER = ""
EMAIL_PASSWORD = ""

LOG_LEVEL = "INFO"
